### ISSUE TITLE
Potential security issue in src/char/int_achievement.cpp: Unchecked return from initialization function

### ISSUE THREAD

**Issue by monocle-ai** [siva-msft/rathena#42]
<span> What is a&nbsp;</span><span><b>Conditionally Uninitialized Variable? </b></span><span> The return value of a function that is potentially used to initialize a local variable is not checked. Therefore, reading the local variable may result in undefined behavior.</span>
---

3 instances of this defect were found in the following locations:
---
**Instance 1**
File : `src/char/int_achievement.cpp` 
Function: `SqlStmt_BindColumn` 
https://github.com/siva-msft/rathena/blob/51425e28b1b03c09f7dcb8243746be095f3d98f4/src/char/int_achievement.cpp#L58
Code extract:

```cpp
		return NULL;
	}

	SqlStmt_BindColumn(stmt, 0, SQLDT_INT,  &tmp_achieve.achievement_id, 0, NULL, NULL); <------ HERE
	SqlStmt_BindColumn(stmt, 1, SQLDT_INT,  &tmp_achieve.completed, 0, NULL, NULL);
	SqlStmt_BindColumn(stmt, 2, SQLDT_INT,  &tmp_achieve.rewarded, 0, NULL, NULL);
```

---
**Instance 2**
File : `src/char/int_achievement.cpp` 
Function: `SqlStmt_BindColumn` 
https://github.com/siva-msft/rathena/blob/51425e28b1b03c09f7dcb8243746be095f3d98f4/src/char/int_achievement.cpp#L59
Code extract:

```cpp
	}

	SqlStmt_BindColumn(stmt, 0, SQLDT_INT,  &tmp_achieve.achievement_id, 0, NULL, NULL);
	SqlStmt_BindColumn(stmt, 1, SQLDT_INT,  &tmp_achieve.completed, 0, NULL, NULL); <------ HERE
	SqlStmt_BindColumn(stmt, 2, SQLDT_INT,  &tmp_achieve.rewarded, 0, NULL, NULL);
	for (i = 0; i < MAX_ACHIEVEMENT_OBJECTIVES; ++i)
```

---
**Instance 3**
File : `src/char/int_achievement.cpp` 
Function: `SqlStmt_BindColumn` 
https://github.com/siva-msft/rathena/blob/51425e28b1b03c09f7dcb8243746be095f3d98f4/src/char/int_achievement.cpp#L60
Code extract:

```cpp

	SqlStmt_BindColumn(stmt, 0, SQLDT_INT,  &tmp_achieve.achievement_id, 0, NULL, NULL);
	SqlStmt_BindColumn(stmt, 1, SQLDT_INT,  &tmp_achieve.completed, 0, NULL, NULL);
	SqlStmt_BindColumn(stmt, 2, SQLDT_INT,  &tmp_achieve.rewarded, 0, NULL, NULL); <------ HERE
	for (i = 0; i < MAX_ACHIEVEMENT_OBJECTIVES; ++i)
		SqlStmt_BindColumn(stmt, 3 + i, SQLDT_INT, &tmp_achieve.count[i], 0, NULL, NULL);
```

**Comment by siva-msft** [comment]
memset(&tmp_achieve, 0, sizeof(tmp_achieve));
initialized in line above
